title: ε-diary
description: 一般人εの思考標本データ
url: "https://epsilon-diary.more-n.net"

timezone: Asia/Tokyo

markdown: kramdown

permalink: /:year-:month-:day-:title

plugins:
  - jekyll-feed
  - jekyll-sitemap